version: "3.9"
services:
  vertica:
    environment:
      APP_DB_USER: "admin"
      APP_DB_PASSWORD: "admin"
      TZ: "Europe/Kyiv"
    container_name: vertica-ce
    image: vertica/vertica-ce
    ports:
      - "5433:5433"
      - "5444:5444"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data2
        target: /data
volumes:
  vertica-data2: